<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="arm_base_width" value="0.1" />
    <xacro:property name="arm_base_length" value="0.1" />
    <xacro:property name="arm_base_height" value="0.02" />
    <xacro:property name="arm_base_mass" value="0.5" />
    <xacro:property name="arm_base_color" value="grey" />

    <xacro:property name="forearm_radius" value="0.02" />
    <xacro:property name="forearm_length" value="0.3" />
    <xacro:property name="forearm_mass" value="0.3" />
    <xacro:property name="forearm_color" value="yellow" />

    <xacro:property name="hand_radius" value="0.02" />
    <xacro:property name="hand_length" value="0.3" />
    <xacro:property name="hand_mass" value="0.3" />
    <xacro:property name="hand_color" value="orange" />


    <link name="arm_base_link">
        <visual>
            <geometry>
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}" />
            </geometry>
            <material name="${arm_base_color}" />
            <origin xyz="0.0 0.0 ${arm_base_height/2}" rpy="0.0 0.0 0.0" />
        </visual>
        <collision>
            <geometry>
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}" />
            </geometry>
            <origin xyz="0.0 0.0 ${arm_base_height/2}" rpy="0.0 0.0 0.0" />
        </collision>
        <xacro:box_inertia m="${arm_base_mass}"
            l="${arm_base_length}" w="${arm_base_width}" h="${arm_base_height}" xyz="0 0 0"
            rpy="0 0 0" />
    </link>

    <xacro:macro name="arm_link" params="name length radius mass color">
        <link name="${name}_link">
            <visual>
                <geometry>
                    <cylinder length="${length}" radius="${radius}" />
                </geometry>
                <origin xyz="0.0 0.0 ${length/2}" rpy="0.0 0.0 0.0" />
                <material name="${color}" />
            </visual>
            <collision>
                <geometry>
                    <cylinder length="${length}" radius="${radius}" />
                </geometry>
                <origin xyz="0.0 0.0 ${length/2}" rpy="0.0 0.0 0.0" />
            </collision>
            <xacro:cylinder_inertia m="${mass}"
                r="${radius}" h="${length}"
                xyz="0 0 0" rpy="0 0 0" />

        </link>
    </xacro:macro>

    <xacro:arm_link name="forearm" length="${forearm_length}" radius="${forearm_radius}"
        mass="${forearm_mass}" color="${forearm_color}" />
    <xacro:arm_link name="hand" length="${hand_length}" radius="${hand_radius}"
        mass="${hand_mass}" color="${hand_color}" />

    <joint name="base_forearm_joint" type="revolute">
        <origin xyz="0.0 0.0 ${arm_base_height}" rpy="0.0 0.0 0.0" />
        <parent link="arm_base_link" />
        <child link="forearm_link" />

        <axis xyz="0 1 0" />
        <limit lower="0.0" upper="${pi/2}" effort="100" velocity="100" />
        <dynamics damping="0.5" friction="0.3" />
    </joint>

    <joint name="forearm_hand_joint" type="revolute">
        <origin xyz="0.0 0.0 ${forearm_length}" rpy="0.0 0.0 0.0" />
        <parent link="forearm_link" />
        <child link="hand_link" />

        <axis xyz="0 1 0" />
        <limit lower="0.0" upper="${pi/2}" effort="100" velocity="100" />
        <dynamics damping="0.1" friction="0.05" />
    </joint>
</robot>