<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="combine_robot">
    <xacro:include filename="material.xacro" />
    <xacro:include filename="inertia.xacro" />

    <xacro:include filename="mobile_base.xacro" />
    <xacro:include filename="mobile_base_gazebo.xacro" />

    <xacro:include filename="camera.xacro" />

    <xacro:include filename="arm_links.xacro" />
    <xacro:include filename="arm_links_gazebo.xacro" />

    <joint name="car_base_joint" type="fixed">
        <origin xyz="${base_length/4} 0.0 ${base_height}" rpy="0.0 0.0 0.0" />
        <parent link="base_link" />
        <child link="arm_base_link" />
    </joint>
</robot>